GET http://localhost:8668/cirtec_dev/top/ref_bundles/

###
GET http://localhost:8668/cirtec_dev/top/ref_authors/

###
GET http://localhost:8668/cirtec_dev/pubs/ref_authors/

###
GET http://localhost:8668/cirtec_dev/ref_auth_bund4ngramm_tops/

###
GET http://localhost:8668/cirtec_dev/ref_bund4ngramm_tops/

###
GET http://localhost:8668/cirtec_dev/ref_auth4ngramm_tops/?topn=5

###
GET http://localhost:8668/cirtec_dev/pos_neg/pubs/

###
GET http://localhost:8668/cirtec_dev/pos_neg/ref_bundles/

###
GET http://localhost:8668/cirtec_dev/pos_neg/ref_authors/

###
GET http://localhost:8668/cirtec_dev/frags/ref_bundles/

###
GET http://localhost:8668/cirtec_dev/frags/ref_authors/

###
GET http://localhost:8668/cirtec_dev/top/ngramms/publications/?ltype=lemmas

###
GET http://localhost:8668/cirtec_dev/publications/

###
GET http://localhost:8668/cirtec_dev/top/topics/

###
GET http://localhost:8668/cirtec_dev/top/topics/publications/

###
GET http://localhost:8668/cirtec_dev/top/ngramms/

###
GET http://localhost:8668/cirtec_dev/publ/cocitauthors/cocitauthors/

###
GET http://localhost:8668/cirtec_dev/pos_neg/contexts/

###
GET http://localhost:8668/cirtec_dev/pos_neg/ngramms/

###
GET http://localhost:8668/cirtec_dev/pos_neg/topics/

###
GET http://localhost:8668/cirtec_dev/pos_neg/cocitauthors/

###
GET http://localhost:8668/cirtec_dev/frags/pos_neg/contexts/

###
GET http://localhost:8668/cirtec_dev/frags/pos_neg/cocitauthors/cocitauthors/

###
GET http://localhost:8668/cirtec_dev/frags/topics/topics/

###
GET http://localhost:8668/cirtec_dev/frags/cocitauthors/cocitauthors/

###
