GET http://localhost:7667/cirtec/frags/

###
GET http://localhost:7667/cirtec/frags/publications/

###
GET http://localhost:7667/cirtec/frags/cocitauthors/

###
GET http://localhost:7667/cirtec/frags/cocitauthors/?topn=5

###
GET http://localhost:7667/cirtec/frags/topics/

###
GET http://localhost:7667/cirtec/frags/topics/?topn=5

###
GET http://localhost:7667/cirtec/frags/ngramm/

###
GET http://localhost:7667/cirtec/frags/ngramm/?topn=5

###
GET http://localhost:7667/cirtec/top/cocitauthors/

###
GET http://localhost:7667/cirtec/top/cocitauthors/?topn=5

###
GET http://localhost:7667/cirtec/top/ngramm/

###
GET http://localhost:7667/cirtec/top/ngramm/?topn=5

###
GET http://localhost:7667/cirtec/top/topics/

###
GET http://localhost:7667/cirtec/top/topics/?topn=5

###
GET http://localhost:7667/cirtec/frags/cocitauthors/ngramms/

###
GET http://localhost:7667/cirtec/frags/cocitauthors/ngramms/?topn=5

###